Access
Afro-Crown/acw-admin-web pull request #6
Opened 2024-03-07 01:55 UTC by claudiosssant

As telas estão prontas, porém o bugzinho dos States ainda persiste. Tentei resolver com a carga restante do meu note. Amanhã vou providenciar um carregador novo até as 13hrs da tarde.

2024-03-13 02:22 UTC, claudiosssant commented
Corrigido graças aos toques do Guilherme! Brabo demais!

2024-03-16 16:00 UTC, GuilhermeArcanjo300 reviewed
Pontos levantados

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on public/registration-in-analysis.svg
public/registration-in-analysis.svg e public/analysis.svg são as mesmas imagens, não poderia deixar apenas uma?

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on public/access-progress-bar-1.svg
Em vez de imagem, poderia ser um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on public/access-progress-bar-2.svg
Em vez de imagem, poderia ser um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on public/access-progress-bar-3.svg
Em vez de imagem, poderia ser um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access-validation/components/password-creation.tsx
> +const PasswordCreation = ({ RedirectPage }: props) => {
Essa propriedade não está sendo usada?

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access-validation/components/validation-code.tsx
> +  RedirectPage: (page: "CODE" | "PASSWORD") => void;
"CODE" | "PASSWORD" é um enum, recomendo colocar em um arquivo separado

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access-validation/page.tsx
> +  const [stage, setStage] = useState<"CODE" | "PASSWORD">("CODE");
"CODE" | "PASSWORD" é um enum, recomendo colocar em um arquivo separado

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access-validation/page.tsx
> +  function RedirectPage(page: "CODE" | "PASSWORD"){
"CODE" | "PASSWORD" é um enum, recomendo colocar em um arquivo separado

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/first-inputs.tsx
> +  RedirectPage:(page: "FIRST" | "SECOND" | "THIRD" | "FOURTH")=> void
"FIRST" | "SECOND" | "THIRD" | "FOURTH" é um enum, recomendo colocar em um arquivo separado. Recomendo deixar mais nitido cada opção, "FIRST" não sei qual pagina é.. sei apenas que é a primeira

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/first-inputs.tsx
> +import progressBar1 from "../../../../../public/access-progress-bar-1.svg";
Recomendo fazer o access-progress-bar como um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/fourth-inputs.tsx
> +import progressBar3 from "../../../../../public/access-progress-bar-3.svg";
Recomendo fazer o access-progress-bar como um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/second-inputs.tsx
> +import progressBar2 from "../../../../../public/access-progress-bar-2.svg";
Recomendo fazer o access-progress-bar como um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/second-inputs.tsx
> +  RedirectPage: (page: "FIRST" | "SECOND" | "THIRD" | "FOURTH") => void;
"FIRST" | "SECOND" | "THIRD" | "FOURTH" é um enum, recomendo colocar em um arquivo separado. Recomendo deixar mais nitido cada opção, "FIRST" não sei qual pagina é.. sei apenas que é a primeira

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/third-inputs.tsx
> +  RedirectPage:(page: "FIRST" | "SECOND" | "THIRD" | "FOURTH")=> void
"FIRST" | "SECOND" | "THIRD" | "FOURTH" é um enum, recomendo colocar em um arquivo separado. Recomendo deixar mais nitido cada opção, "FIRST" não sei qual pagina é.. sei apenas que é a primeira

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/third-inputs.tsx
> +import progressBar3 from "../../../../../public/access-progress-bar-3.svg";
Recomendo fazer o access-progress-bar como um componente

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/components/useMultistepForm.tsx
> +  const [steps, setSteps] = useState<"FIRST" | "SECOND" | "THIRD" | "FOURTH">("FIRST");
"FIRST" | "SECOND" | "THIRD" | "FOURTH" é um enum, recomendo colocar em um arquivo separado. Recomendo deixar mais nitido cada opção, "FIRST" não sei qual pagina é.. sei apenas que é a primeira

2024-03-16 16:00 UTC, GuilhermeArcanjo300 commented on src/app/access/page.tsx
> +              <Link href={"google.com"}>
<Link href={"google.com"}> deixe <Link href={""}> por enquanto

2024-03-20 11:09 UTC, GuilhermeArcanjo300 requested changes

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/first-inputs.tsx
> +import ProgressBar1 from "../progress-bar-1";
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/first-inputs.tsx
> +        <ProgressBar1 />
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/fourth-inputs.tsx
> +import ProgressBar3 from "../progress-bar-3";
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/second-inputs.tsx
> +import ProgressBar2 from "../progress-bar-2";
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/second-inputs.tsx
> +        <ProgressBar2 />
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/third-inputs.tsx
> +import ProgressBar3 from "../progress-bar-3";
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/Stages/third-inputs.tsx
> +        <ProgressBar3 />
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/progress-bar-1.tsx
> +const ProgressBar1 = () => {
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/progress-bar-2.tsx
> +const ProgressBar2 = () => {
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2024-03-20 11:09 UTC, GuilhermeArcanjo300 commented on src/app/access/components/progress-bar-3.tsx
> +const ProgressBar3 = () => {
A ideia é ser apenas um componente de progresso em barra, o tamanho (etapa) será passado atraves de props

2025-03-26 00:10 UTC, closed without merging